objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vlocity_Demo_Image__c</fullName>
        <formula>IF( ISBLANK(Vlocity_Demo_Image_ID__c) , 


IF( RecordType.Name = &apos;Business&apos;, &apos;/resource/VDOCommunityResources/images/profilepicbusiness.png&apos;,  &apos;/resource/VDOCommunityResources/images/profilepicconsumer.png&apos;),


&apos;/servlet/servlet.FileDownload?file=&apos; + Vlocity_Demo_Image_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vlocity Demo Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlocity_Demo_Key__c</fullName>
        <label>Vlocity Demo Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlocity_Demo_Name__c</fullName>
        <label>Vlocity Demo Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__OneTimeTotal__c</fullName>
        <label>Total: One Time Charges</label>
        <summarizedField>OrderItem.vlocity_cmt__OneTimeTotal__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__RecurringTotal__c</fullName>
        <label>Total: Monthly Charges</label>
        <summarizedField>OrderItem.vlocity_cmt__RecurringTotal__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__LineNumber__c</fullName>
        <description>Vlocity line number generated by code which serves to sequence the line items and organize them into a hierarchy.</description>
        <label>LineNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OneTimeTotal__c</fullName>
        <description>Final total after all pricing and * Quantity</description>
        <label>One Time Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__RecurringTotal__c</fullName>
        <description>Final total after all pricing and * Quantity</description>
        <label>Recurring Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

classes/VDOEmailController.cls
global class VDOEmailController{

    public Order theOrder {get;set;}
    public Order theDisplayOrder = new Order();
    public Account theDemoAccount = new Account();
    public Site theSite = new Site();
    public List<VlocityProductWrapper> theProducts = new List<VlocityProductWrapper>();
    
    //Return a set of order items and the corresponding product image
    public List<VlocityProductWrapper> getTheProducts(){
        theSite = [SELECT Name, Status, Subdomain FROM Site WHERE Name = 'Vlocity_Site' LIMIT 1];
        theProducts = new List<VlocityProductWrapper>();
        List<OrderItem> theOrderItems = [SELECT id, vlocity_cmt__OneTimeTotal__c, vlocity_cmt__LineNumber__c, createddate, vlocity_cmt__RecurringTotal__c, PricebookEntry.Product2.Id, PricebookEntry.Product2.Name, PricebookEntry.Product2.Description FROM OrderItem WHERE OrderId = :theOrder.id ORDER BY vlocity_cmt__LineNumber__c ASC];
        Set<Id> theProductSet = new Set<Id>();
        for(OrderItem theOrderItem : theOrderItems){
            theProductSet.add(theOrderItem.PricebookEntry.Product2.Id);
        }
        List<Attachment> theAttachments = [SELECT id, parentid FROM Attachment WHERE Name LIKE 'TN%' AND ParentId IN :theProductSet];
        Map<Id, Attachment> theAttachmentsMap = new Map<Id, Attachment>();
        for(Attachment theAttachment : theAttachments){
            theAttachmentsMap.put(theAttachment.ParentId, theAttachment);
        }
        for(OrderItem theOrderItem: theOrderItems){
            VlocityProductWrapper theWrapper = new VlocityProductWrapper();
            if(theAttachmentsMap.get(theOrderItem.PricebookEntry.Product2.Id) != null){
                theWrapper.theImageURL = 'http://' + theSite.subdomain + '.force.com/servlet/servlet.FileDownload?file=' + theAttachmentsMap.get(theOrderItem.PricebookEntry.Product2.Id).Id;
            }else{
                theWrapper.theImageURL = '#';
            }
            theWrapper.theOrderItem = theOrderItem;
            theProducts.add(theWrapper);
        }
        return theProducts;
    }
    
    public Site getTheSite(){
        theSite = [SELECT Name, Status, Subdomain FROM Site WHERE Name = 'Vlocity_Site' LIMIT 1];
        return theSite;
    }

    public Account getTheDemoAccount(){
        theDemoAccount = [SELECT Vlocity_Demo_Image__c, Vlocity_Demo_Name__c FROM Account WHERE Vlocity_Demo_Key__c = 'demoaccount1' LIMIT 1];
        return theDemoAccount;
    }
    
    public Order getTheDisplayOrder(){
        theDisplayOrder = [SELECT OrderNumber, ActivatedDate, vlocity_cmt__OneTimeTotal__c, vlocity_cmt__RecurringTotal__c FROM Order WHERE id = :theOrder.id];
        return theDisplayOrder;
    }
    
    //A wrapper class used to associate an order item with a product image
    public class VlocityProductWrapper{
        public String theImageURL {get;set;}
        public OrderItem  theOrderItem {get;set;}
    }
}