objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Is_Root__c</fullName>
        <formula>IF(AND(vlocity_cmt__ParentItemId__c = &apos;&apos;, ISPICKVAL(Product2.Family, &apos;Mobile&apos;), ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Offer&apos;)), &apos;true&apos;, &apos;false&apos;)</formula>
        <label>Is Root</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family_Image__c</fullName>
        <formula>IF(ISBLANK(Product_Image__c), 
IF(ISPICKVAL(Product2.Family, &apos;Bundle&apos;),&apos;/resource/VDOProductResources/images/TNBundle.png&apos;,&apos;&apos;)+ 
IF(ISPICKVAL(Product2.Family, &apos;Mobile&apos;),
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Watch&apos;), &apos;/resource/VDOProductResources/images/TNWearable.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Earphones&apos;), &apos;/resource/VDOProductResources/images/TNHeadphones.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Tariff&apos;), &apos;/resource/VDOProductResources/images/TNTariff.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Grant&apos;), &apos;/resource/VDOProductResources/images/TNTariff.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Extra&apos;), &apos;/resource/VDOProductResources/images/TNStar.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Service&apos;), &apos;/resource/VDOProductResources/images/TNStar.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Discount&apos;), &apos;/resource/VDOProductResources/images/TNDiscount.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Offer&apos;), &apos;/resource/VDOProductResources/images/TNStar.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Technology&apos;), &apos;/resource/VDOProductResources/images/TNSim.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__Type__c, &apos;Bundle&apos;), &apos;/resource/VDOProductResources/images/TNBundle.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Handset&apos;), &apos;/resource/VDOProductResources/images/TNMobile.png&apos;,&apos;&apos;),
&apos;&apos;)+
IF(ISPICKVAL(Product2.Family, &apos;Landline&apos;),
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Extra&apos;), &apos;/resource/VDOProductResources/images/TNPhone.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Service&apos;), &apos;/resource/VDOProductResources/images/TNPBX.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Offer&apos;), &apos;/resource/VDOProductResources/images/TNPhone.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Installation&apos;), &apos;/resource/VDOProductResources/images/TNInstall.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Software&apos;), &apos;/resource/VDOProductResources/images/TNPBX.png&apos;,&apos;&apos;),
&apos;&apos;)+
IF(ISPICKVAL(Product2.Family, &apos;Internet&apos;),
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Product&apos;), &apos;/resource/VDOProductResources/images/TNInternet.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Service&apos;), &apos;/resource/VDOProductResources/images/TNLAN.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Technology&apos;), &apos;/resource/VDOProductResources/images/TNPBX.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Installation&apos;), &apos;/resource/VDOProductResources/images/TNInstall.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Software&apos;), &apos;/resource/VDOProductResources/images/TNInternet.png&apos;,&apos;&apos;), 
&apos;&apos;)+
IF(ISPICKVAL(Product2.Family, &apos;Support&apos;),&apos;/resource/VDOProductResources/images/TNSupport.png&apos;,&apos;&apos;)+ 
IF(ISPICKVAL(Product2.Family, &apos;Discount&apos;),&apos;/resource/VDOProductResources/images/TNDiscount.png&apos;,&apos;&apos;)+ 
IF(ISPICKVAL(Product2.Family, &apos;TV&apos;),
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Extra&apos;), &apos;/resource/VDOProductResources/images/TNTV.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Service&apos;), &apos;/resource/VDOProductResources/images/TNTV.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Package&apos;), &apos;/resource/VDOProductResources/images/TNTV.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__SubType__c, &apos;Technology&apos;), &apos;/resource/VDOProductResources/images/TNTV.png&apos;,&apos;&apos;)+ 
          IF(ISPICKVAL(Product2.vlocity_cmt__Type__c, &apos;Bundle&apos;), &apos;/resource/VDOProductResources/images/TNBundle.png&apos;,&apos;&apos;),
&apos;&apos;),
Product_Image__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Broadband - ADSL</fullName>
                </value>
                <value>
                    <fullName>Broadband - Fibre</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>Landline</fullName>
                </value>
                <value>
                    <fullName>Mobile - Contract</fullName>
                </value>
                <value>
                    <fullName>Mobile - Pay As You Go</fullName>
                </value>
                <value>
                    <fullName>Service - Cloud Solutions</fullName>
                </value>
                <value>
                    <fullName>Service - Internet</fullName>
                </value>
                <value>
                    <fullName>Service - Internet Security</fullName>
                </value>
                <value>
                    <fullName>Service - Managed Network</fullName>
                </value>
                <value>
                    <fullName>TV - Equipment</fullName>
                </value>
                <value>
                    <fullName>TV - Package</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__BillingAccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account responsible for paying for the asset.</description>
        <label>Billing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Assets</relationshipLabel>
        <relationshipName>BillingAccountAssets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing Vlocity Attribute data for the asset.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__LineNumber__c</fullName>
        <description>Vlocity line number copied from the order which assists in sequencing the assets and organizing them into a hierarchy.</description>
        <label>Line Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ParentItemId__c</fullName>
        <label>ParentItemId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <description>Formula: Value of the AccountId field.</description>
        <formula>AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing a denormalized representation of the product&apos;s Vlocity Attribute values and configuration metadata.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SubType__c</fullName>
        <description>Product Sub Type can be used to drive implementations/engines, as well as filtering products in the Catalog/Pricebook.  These values may be constrained by the Product Type. If Product Type = &quot;Product&quot; then these values are shown. For Product Type = &quot;Product Bundle&quot; the Sub Type may be NULL</description>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>Earphones</fullName>
                </value>
                <value>
                    <fullName>Extra</fullName>
                </value>
                <value>
                    <fullName>Handset</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Offer</fullName>
                </value>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                    <default>true</default>
                    <label>Product</label>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Tariff</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Watch</fullName>
                </value>
                <value>
                    <fullName>Grant</fullName>
                </value>
                <value>
                    <fullName>Device</fullName>
                </value>
                <value>
                    <fullName>Rate Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <description>Product Type can be used to drive eligibility/compatibility/recommendations/other implementations</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product</fullName>
                    <default>true</default>
                    <label>Product</label>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>Promotion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__CustomerInteraction__c.object
<CustomObject>
    <description>An interaction between a customer, prospect, partner or other contact and your organization. Could be a phone call, a web site visit, a mobile application session or an in-person meeting.</description>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Interactions</relationshipLabel>
        <relationshipName>CustomerInteractions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Interactions</relationshipLabel>
        <relationshipName>CustomerInteractions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Appointment</fullName>
                </value>
                <value>
                    <fullName>Drop In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Interaction</label>
    <nameField>
        <label>Customer Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__CustomerInteractionTopic__c.object
<CustomObject>
    <description>A topic discussed or addressed during a customer interaction such as a customer account, a customer asset, a quote or a case. A topic could even be a specific field or aspect of an object such as a charge on a bill or a co-pay on a health insurance coverage.</description>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Interaction Topics</relationshipLabel>
        <relationshipName>CustomerInteractionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Customer Interaction Topics</relationshipLabel>
        <relationshipName>CustomerInteractionTopics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__CustomerInteractionId__c</fullName>
        <label>Customer Interaction</label>
        <referenceTo>vlocity_cmt__CustomerInteraction__c</referenceTo>
        <relationshipLabel>Customer Interaction Topics</relationshipLabel>
        <relationshipName>CustomerInteractionTopics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Interaction Topic</label>
    <nameField>
        <label>Customer Interaction Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Interaction Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VDOGetInteractionAssetsV2.cls
global with sharing class VDOGetInteractionAssetsV2 implements vlocity_cmt.VlocityOpenInterface2
{
    public Object invokeMethod(String methodName,Map<String,Object> inputs, Map<String,Object> output, Map<String,Object> options)
    {
        Boolean success = true;
        try{
            if(methodName == 'getInteractionAssets')
            {
                getInteractionAssets(inputs, output, options);
            }
            
        }catch(Exception e){
            System.debug('Error invoke method: ' + methodName + ' with error: '+ e);
            success = false;
        }
        return success;
    }

    private void getInteractionAssets(Map<String,Object> inputMap,  Map<String,Object> outMap, Map<String,Object> options)
    {
        String interactionId = String.valueOf(inputMap.get('interactionId'));
        System.debug('interaction id is '+interactionId);
        //List<vlocity_cmt__CustomerInteraction__c> interactions = [Select vlocity_cmt__AccountId__c, vlocity_cmt__ContactId__c from vlocity_cmt__CustomerInteraction__c where Id =:interactionId];
        //System.debug('interactions are '+interactions);
      
        if(String.isNotBlank(interactionId)) 
        {
            List<Map<String, Object>> listOfResults = new List<Map<String, Object>>();
            List<vlocity_cmt__CustomerInteractionTopic__c> iTopics= [SELECT Id, vlocity_cmt__AccountId__c, Name, Roles__c, vlocity_cmt__AssetId__c FROM vlocity_cmt__CustomerInteractionTopic__c WHERE vlocity_cmt__CustomerInteractionId__c = :interactionId ORDER BY CreatedDate];
            if(iTopics != null && iTopics.size() > 0)
            {
                //Set<Id> accountIds = new Set<Id>();
                Map<Id, String> accountRolesMap = new Map<Id, String>();
                //Map<Id, String> assetRolesMap = new Map<Id, String>();
                Map<Id, Id> assetTopicMap = new Map<Id, Id>();
                for(vlocity_cmt__CustomerInteractionTopic__c it:iTopics)
                {
                    //accountIds.add(it.vlocity_cmt__AccountId__c);
                    accountRolesMap.put(it.vlocity_cmt__AccountId__c, it.Roles__c);
                    assetTopicMap.put(it.vlocity_cmt__AssetId__c, it.Id);
                }
                //System.debug('accountIds: ' + accountIds);
                System.debug('accountRolesMap'+ accountRolesMap + ' assetTopicMap: ' + assetTopicMap);
                //get list of assets for accountIds
                List<Asset> assets = [SELECT Id,vlocity_cmt__ParentItemId__c,Is_Root__c,AccountId,Account.Name,LastModifiedDate,Product2.Name,Product2.vlocity_cmt__Type__c,Product2.vlocity_cmt__JSONAttribute__c, Product2.Family, Product2.vlocity_cmt__SubType__c ,vlocity_cmt__BillingAccountId__r.Name,Name, Price,SerialNumber, vlocity_cmt__LineNumber__c, Product_Family__c,Product_Family_Image__c, PurchaseDate,InstallDate,Status,Mobile_Number__c, vlocity_cmt__RecurringTotal__c,Description, Quantity, AssetCategory__c FROM Asset WHERE Id in :assetTopicMap.keySet() AND (vlocity_cmt__LineNumber__c LIKE '____.____' OR vlocity_cmt__LineNumber__c LIKE '____') ORDER BY Account.Name, vlocity_cmt__LineNumber__c];
                if(assets != null && assets.size() > 0)
                {
                    for (Asset ast: assets)
                    {
                        Map<String, Object> result = new Map<String, Object>();
                        result.put('InteractionId', interactionId);
                        result.put('InteractionTopicId', assetTopicMap.get(ast.Id));
                        result.put('AccountId', ast.AccountId);
                        result.put('Id', ast.Id);
                        result.put('vlocity_cmt__ParentItemId__c', ast.vlocity_cmt__ParentItemId__c);
                        result.put('Is_Root__c', ast.Is_Root__c);
                        result.put('Account_Name', ast.Account.Name);
                        result.put('ContactRoles', accountRolesMap.get(ast.AccountId));
                        result.put('LastModifiedDate', ast.LastModifiedDate);
                        result.put('Product2_Name', ast.Product2.Name);
                        result.put('Product2_vlocity_cmt__Type__c', ast.Product2.vlocity_cmt__Type__c);
                        result.put('Product2_vlocity_cmt__JSONAttribute__c', ast.Product2.vlocity_cmt__JSONAttribute__c);
                        result.put('Product2_Family', ast.Product2.Family);
                        result.put('Product2_vlocity_cmt__SubType__c', ast.Product2.vlocity_cmt__SubType__c);
                        result.put('vlocity_cmt__BillingAccountId__r_Name', ast.vlocity_cmt__BillingAccountId__r.Name);
                        result.put('Name', ast.Name);
                        result.put('Price', ast.Price);
                        result.put('SerialNumber', ast.SerialNumber);
                        result.put('vlocity_cmt__LineNumber__c', ast.vlocity_cmt__LineNumber__c);
                        result.put('Product_Family__c', ast.Product_Family__c);
                        result.put('Product_Family_Image__c', ast.Product_Family_Image__c);
                        result.put('PurchaseDate', ast.PurchaseDate);
                        result.put('InstallDate', ast.InstallDate);
                        result.put('Status', ast.Status);
                        result.put('Mobile_Number__c', ast.Mobile_Number__c);
                        result.put('vlocity_cmt__RecurringTotal__c', ast.vlocity_cmt__RecurringTotal__c);
                        result.put('Description', ast.Description);
                        result.put('Quantity', ast.Quantity);
                        result.put('AssetCategory__c', ast.AssetCategory__c);
                        listOfResults.add(result);
                    }
                    system.debug('listOfResults: ' + listofResults);
                    outMap.put('records', listOfResults);
                }
            }
        }

    }
}